name:                TheBindingOfRichard
version:             0.1.0.0
github:              "benkio/TheBindingOfRichard"
license:             BSD3
author:              "Enrico Benini"
maintainer:          "benkio89@gmail.com"
copyright:           "2022 Enrico Benini"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/benkio/TheBindingOfRichard#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- random
- sdl2

library:
  source-dirs: src

executables:
  TheBindingOfRichard-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TheBindingOfRichard

tests:
  TheBindingOfRichard-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TheBindingOfRichard
