name: CI

on:
  pull_request:
    types: [opened, reopened]
  push:
    branches:
        - "**"

jobs:
  fourmolu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: "Apply Fourmolu"
      uses: haskell-actions/run-fourmolu@v7

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: haskell/actions/setup@v2
      with:
        ghc-version: '9.2.8' # Exact version of ghc to use
        # cabal-version: 'latest'. Omitted, but defaults to 'latest'
        enable-stack: true
        stack-version: 'latest'
    - name: "Unit tests"
      run: "stack test"

  hlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: 'Set up HLint'
      uses: haskell/actions/hlint-setup@v2

    - name: 'Run HLint src'
      uses: haskell/actions/hlint-run@v2
      with:
        path: src/
        fail-on: warning

    - name: 'Run HLint test'
      uses: haskell/actions/hlint-run@v2
      with:
        path: test/
        fail-on: warning
