name: CI

on:
  pull_request:
    types: [opened, reopened]
  push:
    branches:
        - "**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ormolu-action
      uses: mrkkrp/ormolu-action@v7
    - uses: actions/checkout@v2

    - name: 'Set up HLint'
      uses: rwe/actions-hlint-setup@v1
      with:
        version: '3.5'

    - name: 'Run HLint'
      uses: rwe/actions-hlint-run@v2
      with:
        path: src/
        fail-on: warning
